name: Publish Release
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ“© checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: ğŸª„ publish executable
        run: |
          dotnet publish ./src/Signature/Signature.csproj --runtime win-x64 --configuration Release --output publish/win64 --no-self-contained /p:PublishSingleFile=true
      
      - name: ğŸ’¾ upload executable to workflow
        uses: actions/upload-artifact@v4
        with:
          name: "signature-win64.exe"
          path: "publish/win64/Signature.exe"
          if-no-files-found: 'error'
          retention-days: 90
          compression-level: 0
          overwrite: 'true'
          
      - name: ğŸ’¾ upload release executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet publish ./src/Signature/Signature.csproj --runtime win-x64 --configuration Release --output publish/win64 --no-self-contained /p:PublishSingleFile=true
          echo ${{ github.ref_name }}
          gh release upload "${{ github.ref_name }}" ./publish/win64/Signature.exe