name: Publish Release
on:
  release:
    types:
      - published
jobs:
  publish:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ“© checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: ğŸ—ï¸ install packages
        run: |
          sudo apt update
          sudo apt install zip

      # There's a few commands in a row here, let's explain them:
      # Publish windows x64 artifact
      # Copy the readme
      # Move into the 'publish' directory
      # Zip all the files
      - name: ğŸª„ publish executable
        run: |
          dotnet publish ./src/Signature/Signature.csproj --runtime win-x64 --output publish
          cp readme.md publish/readme.md
          cd publish
          zip "../signature-v${{ github.ref_name }}.zip" *
        
      - name: ğŸ’¾ upload release executable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.ref_name }}" "signature-v${{ github.ref_name }}.zip"